pyaggr3g470r/models/article.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

# pyAggr3g470r - A Web based news aggregator.
# Copyright (C) 2010-2015  Cédric Bonhomme - https://www.cedricbonhomme.org
#
# For more information : https://bitbucket.org/cedricbonhomme/pyaggr3g470r
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

__author__ = "Cedric Bonhomme"
__version__ = "$Revision: 0.4 $"
__date__ = "$Date: 2013/11/05 $"
__revision__ = "$Date: 2014/04/12 $"
__copyright__ = "Copyright (c) Cedric Bonhomme"
__license__ = "GPLv3"

import json
from bootstrap import db
from datetime import datetime
from sqlalchemy import asc, desc


class Article(db.Model):
    """
    Represent an article from a feed.
    """
    id = db.Column(db.Integer, primary_key=True)
    entry_id = db.Column(db.String())
    link = db.Column(db.String())
    title = db.Column(db.String())
    content = db.Column(db.String())
    readed = db.Column(db.Boolean(), default=False)
    like = db.Column(db.Boolean(), default=False)
    date = db.Column(db.DateTime(), default=datetime.now)
    retrieved_date = db.Column(db.DateTime(), default=datetime.now)

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    feed_id = db.Column(db.Integer, db.ForeignKey('feed.id'))

    def previous_article(self):
        """
        Returns the previous article (older).
        """
        return Article.query.filter(Article.date < self.date,
                                    Article.feed_id == self.feed_id)\
                            .order_by(desc("Article.date")).first()

    def next_article(self):
        """
        Returns the next article (newer).
        """
        return Article.query.filter(Article.date > self.date,
                                    Article.feed_id == self.feed_id)\
                            .order_by(asc("Article.date")).first()

    def __repr__(self):
        return json.dumps({"title": self.title,
                           "link": self.link,
                           "content": self.content
                           })

    def dump(self):
        return {"id": self.id,
                "user_id": self.user_id,
                "entry_id": self.entry_id,
                "title": self.title,
                "link": self.link,
                "content": self.content,
                "readed": self.readed,
                "like": self.like,
                "date": self.date,
                "retrieved_date": self.retrieved_date,
                "feed_id": getattr(self.source, 'id', None),
                "feed_name": getattr(self.source, 'title', None)}

pyaggr3g470r/models/feed.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

# pyAggr3g470r - A Web based news aggregator.
# Copyright (C) 2010-2015  Cédric Bonhomme - https://www.cedricbonhomme.org
#
# For more information : https://bitbucket.org/cedricbonhomme/pyaggr3g470r/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

__author__ = "Cedric Bonhomme"
__version__ = "$Revision: 0.4 $"
__date__ = "$Date: 2013/11/05 $"
__revision__ = "$Date: 2014/04/12 $"
__copyright__ = "Copyright (c) Cedric Bonhomme"
__license__ = "GPLv3"

from bootstrap import db
from datetime import datetime
from sqlalchemy import desc


class Feed(db.Model):
    """
    Represent a feed.
    """
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(), default="")
    description = db.Column(db.String(), default="FR")
    link = db.Column(db.String())
    site_link = db.Column(db.String(), default="")
    enabled = db.Column(db.Boolean(), default=True)
    created_date = db.Column(db.DateTime(), default=datetime.now)

    # cache handling
    etag = db.Column(db.String(), default="")
    last_modified = db.Column(db.String(), default="")
    last_retrieved = db.Column(db.DateTime(), default=datetime(1970, 1, 1))

    # error logging
    last_error = db.Column(db.String(), default="")
    error_count = db.Column(db.Integer(), default=0)

    # relationship
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    articles = db.relationship('Article', backref='source', lazy='dynamic',
                               cascade='all,delete-orphan',
                               order_by=desc("Article.date"))

    def __repr__(self):
        return '<Feed %r>' % (self.title)

    def dump(self):
        return {"id": self.id,
                "user_id": self.user_id,
                "title": self.title,
                "description": self.description,
                "link": self.link,
                "site_link": self.site_link,
                "etag": self.etag,
                "error_count": self.error_count,
                "last_modified": self.last_modified,
                "last_retrieved": self.last_retrieved}

pyaggr3g470r/controllers/article.py
from sqlalchemy import func

from bootstrap import db
from .abstract import AbstractController
from pyaggr3g470r.models import Article


class ArticleController(AbstractController):
    _db_cls = Article

    def get(self, **filters):
        article = super(ArticleController, self).get(**filters)
        if not article.readed:
            self.update({'id': article.id}, {'readed': True})
        return article

    def challenge(self, ids):
        """Will return each id that wasn't found in the database."""
        for id_ in ids:
            if self.read(**id_).first():
                continue
            yield id_

    def get_unread(self):
        return dict(db.session.query(Article.feed_id, func.count(Article.id))
                       .filter(*self._to_filters(readed=False,
                                                 user_id=self.user_id))
                       .group_by(Article.feed_id).all())

pyaggr3g470r/controllers/feed.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

# pyAggr3g470r - A Web based news aggregator.
# Copyright (C) 2010-2015  Cédric Bonhomme - https://www.cedricbonhomme.org
#
# For more information : https://bitbucket.org/cedricbonhomme/pyaggr3g470r/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import logging
from datetime import datetime, timedelta

import conf
from .abstract import AbstractController
from pyaggr3g470r.models import Feed

logger = logging.getLogger(__name__)
DEFAULT_LIMIT = 5
DEFAULT_REFRESH_RATE = 60
DEFAULT_MAX_ERROR = conf.DEFAULT_MAX_ERROR


class FeedController(AbstractController):
    _db_cls = Feed

    def list_late(self, max_last, max_error=DEFAULT_MAX_ERROR,
                  limit=DEFAULT_LIMIT):
        return [feed for feed in self.read(
                            error_count__lt=max_error, enabled=True,
                            last_retrieved__lt=max_last)
                                .order_by('Feed.last_retrieved')
                                .limit(limit)]

    def list_fetchable(self, max_error=DEFAULT_MAX_ERROR, limit=DEFAULT_LIMIT,
                       refresh_rate=DEFAULT_REFRESH_RATE):
        now = datetime.now()
        max_last = now - timedelta(minutes=refresh_rate)
        feeds = self.list_late(max_last, max_error, limit)
        if feeds:
            self.update({'id__in': [feed.id for feed in feeds]},
                        {'last_retrieved': now})
        return feeds

pyaggr3g470r/views/article.py
#! /usr/bin/env python
# -*- coding: utf-8 -

from flask import Blueprint, g, render_template, redirect
from sqlalchemy import desc

from pyaggr3g470r import controllers, utils
from pyaggr3g470r.decorators import pyagg_default_decorator

articles_bp = Blueprint('articles', __name__, url_prefix='/articles')
article_bp = Blueprint('article', __name__, url_prefix='/article')


@article_bp.route('/redirect/<int:article_id>', methods=['GET'])
@pyagg_default_decorator
def redirect_to_article(article_id):
    article = controllers.ArticleController(g.user.id).get(id=article_id)
    return redirect(article.link)


@article_bp.route('/<int:article_id>', methods=['GET'])
@pyagg_default_decorator
def article(article_id=None):
    """
    Presents the content of an article.
    """
    article = controllers.ArticleController(g.user.id).get(id=article_id)
    previous_article = article.previous_article()
    if previous_article is None:
        previous_article = article.source.articles[0]
    next_article = article.next_article()
    if next_article is None:
        next_article = article.source.articles[-1]

    return render_template('article.html',
                           head_titles=[utils.clear_string(article.title)],
                           article=article,
                           previous_article=previous_article,
                           next_article=next_article)

pyaggr3g470r/views/feed.py
#! /usr/bin/env python
# -*- coding: utf-8 -

from datetime import datetime
from sqlalchemy import desc
from werkzeug.exceptions import BadRequest

from flask import Blueprint, g, render_template, flash, \
                  redirect, request, url_for
from flask.ext.babel import gettext
from flask.ext.login import login_required

import conf
from pyaggr3g470r import utils
from pyaggr3g470r.forms import AddFeedForm
from pyaggr3g470r.controllers import FeedController, ArticleController

feeds_bp = Blueprint('feeds', __name__, url_prefix='/feeds')
feed_bp = Blueprint('feed', __name__, url_prefix='/feed')


@feeds_bp.route('/', methods=['GET'])
@login_required
def feeds():
    "Lists the subscribed  feeds in a table."
    return render_template('feeds.html',
            feeds=FeedController(g.user.id).read())


@feed_bp.route('/<int:feed_id>', methods=['GET'])
@login_required
def feed(feed_id=None):
    "Presents detailed information about a feed."
    feed = FeedController(g.user.id).get(id=feed_id)
    word_size = 6
    articles = ArticleController(g.user.id) \
            .read(feed_id=feed_id) \
            .order_by(desc("Article.date")).all()
    top_words = utils.top_words(articles, n=50, size=int(word_size))
    tag_cloud = utils.tag_cloud(top_words)

    today = datetime.now()
    try:
        last_article = articles[0].date
        first_article = articles[-1].date
        delta = last_article - first_article
        average = round(float(len(articles)) / abs(delta.days), 2)
    except:
        last_article = datetime.fromtimestamp(0)
        first_article = datetime.fromtimestamp(0)
        delta = last_article - first_article
        average = 0
    elapsed = today - last_article

    return render_template('feed.html',
                           head_titles=[utils.clear_string(feed.title)],
                           feed=feed, tag_cloud=tag_cloud,
                           first_post_date=first_article,
                           end_post_date=last_article,
                           average=average, delta=delta, elapsed=elapsed)


@feed_bp.route('/delete/<feed_id>', methods=['GET'])
@login_required
def delete(feed_id=None):
    feed_contr = FeedController(g.user.id)
    feed = feed_contr.get(id=feed_id)
    feed_contr.delete(feed_id)
    flash(gettext("Feed %(feed_title)s successfully deleted.",
                  feed_title=feed.title), 'success')
    return redirect(url_for('home'))


@feed_bp.route('/reset_errors/<int:feed_id>', methods=['GET', 'POST'])
@login_required
def reset_errors(feed_id):
    feed_contr = FeedController(g.user.id)
    feed = feed_contr.get(id=feed_id)
    feed_contr.update({'id': feed_id}, {'error_count': 0, 'last_error': ''})
    flash(gettext('Feed %(feed_title)r successfully updated.',
                  feed_title=feed.title), 'success')
    return redirect(request.referrer or url_for('home'))


@feed_bp.route('/bookmarklet', methods=['GET'])
@login_required
def bookmarklet():
    feed_contr = FeedController(g.user.id)
    url = request.args.get('url', None)
    if not url:
        flash(gettext("Couldn't add feed: url missing."), "error")
        raise BadRequest("url is missing")

    existing_feeds = list(feed_contr.read(link=url))
    if existing_feeds:
        flash(gettext("Couldn't add feed: feed already exists."),
                "warning")
        return redirect(url_for('feed.form',
                                feed_id=existing_feeds[0].id))

    feed = feed_contr.create(link=url)
    flash(gettext('Feed was successfully created.'), 'success')
    if conf.CRAWLING_METHOD == "classic":
        utils.fetch(g.user.id, feed.id)
        flash(gettext("Downloading articles for the new feed..."), 'info')
    return redirect(url_for('feed.form', feed_id=feed.id))


@feed_bp.route('/read/<int:feed_id>', methods=['GET', 'POST'])
@login_required
def read(feed_id):
    FeedController(g.user.id).update(readed=True)
    flash(gettext('Feed successfully updated.',
                  feed_title=feed.title), 'success')
    return redirect(request.referrer or url_for('home'))


@feed_bp.route('/update/<action>/<int:feed_id>', methods=['GET', 'POST'])
@feeds_bp.route('/update/<action>', methods=['GET', 'POST'])
@login_required
def update(action, feed_id=None):
    readed = action == 'read'
    filters = {'readed__ne': readed}
    if feed_id:
        filters['feed_id'] = feed_id
    ArticleController(g.user.id).update(filters, {'readed': readed})
    flash(gettext('Feed successfully updated.'), 'success')
    return redirect(request.referrer or url_for('home'))


@feed_bp.route('/create', methods=['GET', 'POST', 'PUT'])
@feed_bp.route('/edit/<int:feed_id>', methods=['GET', 'POST'])
@login_required
def form(feed_id=None):
    form = AddFeedForm()
    feed_contr = FeedController(g.user.id)

    if request.method == 'POST':
        if not form.validate():
            return render_template('edit_feed.html', form=form)
        existing_feeds = list(feed_contr.read(link=form.link.data))
        if existing_feeds and feed_id is None:
            flash(gettext("Couldn't add feed: feed already exists."),
                  "warning")
            return redirect(url_for('feed.form',
                                    feed_id=existing_feeds[0].id))
        # Edit an existing feed
        if feed_id is not None:
            feed_contr.update({'id': feed_id},
                              {'title': form.title.data,
                               'link': form.link.data,
                               'enabled': form.enabled.data,
                               'site_link': form.site_link.data})
            flash(gettext('Feed %(feed_title)r successfully updated.',
                          feed_title=form.title.data), 'success')
            return redirect(url_for('feed.form', feed_id=feed_id))

        # Create a new feed
        new_feed = FeedController(g.user.id).create(
                        title=form.title.data,
                        description="",
                        link=form.link.data,
                        site_link=form.site_link.data,
                        enabled=form.enabled.data)

        flash(gettext('Feed %(feed_title)r successfully created.',
                      feed_title=new_feed.title), 'success')

        if conf.CRAWLING_METHOD == "classic":
            utils.fetch(g.user.id, new_feed.id)
            flash(gettext("Downloading articles for the new feed..."), 'info')

        return redirect(url_for('feed.form',
                                feed_id=new_feed.id))

    # Getting the form for an existing feed
    if feed_id is not None:
        feed = FeedController(g.user.id).get(id=feed_id)
        form = AddFeedForm(obj=feed)
        return render_template('edit_feed.html',
                               action=gettext("Edit the feed"),
                               form=form, feed=feed)

    # Return an empty form in order to create a new feed
    return render_template('edit_feed.html', action=gettext("Add a feed"),
                           form=form)

pyaggr3g470r/templates/edit_feed.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="well">
        <h1>{{ action }}</h1>
        <form action="" method="post" name="save">
            {{ form.hidden_tag() }}

            {{ form.link.label }}
            {{ form.link(class_="form-control") }} {% for error in form.link.errors %} <span style="color: red;">{{ error }}<br /></span>{% endfor %}

            {{ form.title.label }}
            {{ form.title(class_="form-control", placeholder=_('Optional')) }} {% for error in form.title.errors %} <span style="color: red;">{{ error }}<br /></span>{% endfor %}

            {{ form.site_link.label }}
            {{ form.site_link(class_="form-control", placeholder=_('Optional')) }} {% for error in form.site_link.errors %} <span style="color: red;">{{ error }}<br /></span>{% endfor %}

            {{ form.enabled.label }}
            {{ form.enabled(class_="checkbox") }}
            <br />
            {{ form.submit(class_="btn btn-default") }}
        </form>
    </div>
</div><!-- /.container -->
{% endblock %}

pyaggr3g470r/templates/feed.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="well">
        <h2>{{ feed.title }}</h2>
        {% if feed.description %} <p>{{ feed.description }}</p> {% endif %}
        <a href="{{ url_for("feed.delete", feed_id=feed.id) }}"><i class="glyphicon glyphicon-remove" title="{{ _('Delete this feed') }}" onclick="return confirm('{{ _('You are going to delete this feed.') }}');"></i></a>
        <a href="{{ url_for("feed.form", feed_id=feed.id) }}"><i class="glyphicon glyphicon-edit" title="{{ _('Edit this feed') }}"></i></a>
    </div>
    <div class="well">
        <p>
        {{ _('This feed contains') }} {{ feed.articles.all()|count }} <a href= "{{ url_for("home", feed_id=feed.id, filter_="all")  }}">{{ _('articles') }}</a>.<br />
        {{ _('Address of the feed') }}: <a href="{{ feed.link }}" target="_blank">{{ feed.link }}</a><br />
        {% if feed.site_link != "" %}
            {{ _('Address of the site') }}: <a href="{{ feed.site_link }}" target="_blank">{{ feed.site_link }}</a><br />
        {% endif %}

        <br />

        {% if feed.last_retrieved %}
            {{ _("Last download:") }} {{ feed.last_retrieved | datetime }}<br />
        {% endif %}

        {% if feed.error_count > 2 %}
            <b>{{ _("That feed has encountered too much consecutive errors and won't be retrieved anymore.") }}</b><br />
            {{ _("You can click <a href='%(reset_error_url)s'>here</a> to reset the error count and reactivate the feed.", reset_error_url=url_for("feed.reset_errors", feed_id=feed.id)) }}
        {% elif feed.error_count > 0 %}
            {{ _("The download of this feed has encountered some problems. However its error counter will be reinitialized at the next successful retrieving.") }}<br />
        {% endif %}

        {% if feed.last_error %}
            {{ _("Here's the last error encountered while retrieving this feed:") }} <pre>{{ feed.last_error }}</pre><br />
        {% endif %}

        {% if feed.articles.all()|count != 0 %}
            {{ _('The last article was posted') }} {{ elapsed.days }} {{ _('day(s) ago.') }}<br />
            {{ _('Daily average') }}: {{ average }}, {{ _('between the') }} {{ first_post_date | datetime }} {{ _('and the') }} {{ end_post_date | datetime }}.
        {% endif %}
        </p>
    </div>
    <div class="well">
        {% if feed.articles.all()|count != 0 %}
            <div>{{ tag_cloud|safe }}</div>
        {% endif %}
    </div>
</div><!-- /.container -->
{% endblock %}

pyaggr3g470r/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% if feeds|count == 0 %}
    <div class="col-md-4 col-md-offset-4">
        <h1>{{ _("You don't have any feeds.") }}</h1>
        <h1><a href="{{ url_for("feed.form") }}">{{ _('Add some') }}</a>, {{ _('or') }} <a href="/management">{{ _('upload an OPML file.') }}</a></h1>
    </div>
{% else %}
    <div id="affix-nav" class="col-md-3 sidebar hidden-xs hidden-sm">
        <ul class="nav sidenav navbar-collapse pre-scrollable" data-offset-top="0" data-offset-bottom="0" style="min-height: 650px;">
            <li><a href="{{ gen_url(feed_id=0) }}">
                {% if not feed_id %}<b>{% endif %}
                  {{ _('All feeds') }} <span id="total-unread" class="badge pull-right">{{ articles.__len__() }}</span>
                {% if not feed_id %}</b>{% endif %}
            </a></li>
        {% for fid, nbunread in unread|dictsort(by='value')|reverse %}
            <li class="feed-menu"><a href="{{ gen_url(feed_id=fid) }}">
                {% if feed_id == fid %}<b>{% endif %}
                    {% if in_error.get(fid, 0) > 0 %}
                        <span style="background-color: {{ "red" if in_error[fid] > conf.DEFAULT_MAX_ERROR -1 else "orange" }} ;" class="badge pull-right" title="Some errors occured while trying to retrieve that feed.">{{ in_error[fid] }} {{ _("error") }}{% if in_error[fid] > 1 %}s{% endif %}</span>
                    {% endif %}
                    <span id="unread-{{ fid }}" class="badge pull-right">{{ nbunread }}</span>
                    {{ feeds[fid]|safe }}
                {% if feed_id == fid %}</b>{% endif %}
            </a></li>
            <li class="feed-commands"><span>
                <a href="/feed/{{ fid }}"><i class="glyphicon glyphicon-info-sign" title="{{ _('Details') }}"></i></a>
                <a href="{{ url_for("feed.form", feed_id=fid) }}"><i class="glyphicon glyphicon-edit" title="{{ _('Edit this feed') }}"></i></a>
                <a href="{{ url_for("feed.delete", feed_id=fid) }}"><i class="glyphicon glyphicon-remove" title="{{ _('Delete this feed') }}" onclick="return confirm('{{ _('You are going to delete this feed.') }}');"></i></a>
                <a href="{{ url_for("feed.update", feed_id=fid, action="read") }}"><i class="glyphicon glyphicon-check" title="{{ _('Mark this feed as read') }}"></i></a>
                <a href="{{ url_for("feed.update", feed_id=fid, action="unread") }}"><i class="glyphicon glyphicon-unchecked" title="{{ _('Mark this feed as unread') }}"></i></a>
            </span></li>
        {% endfor %}
        {% for fid, ftitle in feeds|dictsort(case_sensitive=False, by='value') if not fid in unread %}
            <li class="feed-menu"><a href="{{ gen_url(feed_id=fid) }}">
                {% if in_error.get(fid, 0) > 0 %}
                    <span style="background-color: {{ "red" if in_error[fid] > conf.DEFAULT_MAX_ERROR - 1 else "orange" }} ;" class="badge pull-right" title="Some errors occured while trying to retrieve that feed.">{{ in_error[fid] }} {{ _("error") }}{% if in_error[fid] > 1 %}s{% endif %}</span>
                {% endif %}
                {% if feed_id == fid %}<b>{% endif %}
                    {{ ftitle|safe }}
                {% if feed_id == fid %}</b>{% endif %}
            </a></li>
            <li class="feed-commands"><span>
                <a href="{{ url_for("feed.feed", feed_id=fid) }}"><i class="glyphicon glyphicon-info-sign" title="{{ _('Details') }}"></i></a>
                <a href="{{ url_for("feed.form", feed_id=fid) }}"><i class="glyphicon glyphicon-edit" title="{{ _('Edit this feed') }}"></i></a>
                <a href="{{ url_for("feed.delete", feed_id=fid) }}"><i class="glyphicon glyphicon-remove" title="{{ _('Delete this feed') }}" onclick="return confirm('{{ _('You are going to delete this feed.') }}');"></i></a>
                <a href="{{ url_for("feed.update", feed_id=fid, action="read") }}"><i class="glyphicon glyphicon-check" title="{{ _('Mark this feed as read') }}"></i></a>
                <a href="{{ url_for("feed.update", feed_id=fid, action="unread") }}"><i class="glyphicon glyphicon-unchecked" title="{{ _('Mark this feed as unread') }}"></i></a>
            </span></li>
        {% endfor %}
        </ul>
    </div>
    <div class="container col-md-9">
        <div id="filters" data-filter="{{ filter_ }}">
            <ul id="myTab" class="nav nav-tabs" role="tablist">
                <li id="tab-all"><a href="{{ gen_url(filter_='all') }}">{{ _('All') }}</a></li>
                <li id="tab-read"><a href="{{ gen_url(filter_='read') }}">{{ _('Read') }}</a></li>
                <li id="tab-unread"><a href="{{ gen_url(filter_='unread') }}">{{ _('Unread') }}</a></li>
                <li id="tab-nbdisplay" class="pull-right">
                    <div id="nbdisplay">
                        <a href="{{ gen_url(limit=10) }}" class="label {% if limit == 10 %}label-primary{% else %}label-info{% endif %}">{{ _(10) }}</a>
                        <a href="{{ gen_url(limit=100) }}" class="label {% if limit == 100 %}label-primary{% else %}label-info{% endif %}">{{ _(100) }}</a>
                        <a href="{{ gen_url(limit=1000) }}" class="label {% if limit == 1000 %}label-primary{% else %}label-info{% endif %}">{{ _(1000) }}</a>
                        <a href="{{ gen_url(limit='all') }}" class="label {% if limit == 'all' %}label-primary{% else %}label-info{% endif %}">{{ _('All') }}</a>
                    </div>
                </li>
        </div>
        {% if articles | count != 0%}
            <div class="table-responsive">
                <table class="table table-striped strict-table">
                    <thead>
                        <tr>
                            <th></th>
                            <th><a href="{{ gen_url(sort_='-feed' if sort_ == 'feed' else 'feed') }}">{{ _('Feed') }}</a></th>
                            <th><a href="{{ gen_url(sort_='-article' if sort_ == 'article' else 'article') }}">{{ _('Article') }}</a></th>
                            <th><a href="{{ gen_url(sort_='-date' if sort_ == 'date' else 'date') }}">{{ _('Date') }}</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for article in articles %}
                        <tr data-article="{{ article.id }}" data-feed="{{ article.feed_id }}">
                            <td>
                                <a><i class="glyphicon glyphicon-remove delete" title="{{ _('Delete this article') }}"></i></a>
                                {% if article.like %}
                                    <a><i class="glyphicon glyphicon-star like" title="{{ _('One of your favorites') }}"></i></a>
                                {% else %}
                                    <a><i class="glyphicon glyphicon-star-empty like" title="{{ _('Click if you like this article') }}"></i></a>
                                {% endif %}
                                {% if article.readed %}
                                    <a><i class="glyphicon glyphicon-unchecked readed" title="{{ _('Mark this article as unread') }}"></i></a>
                                {% else %}
                                    <a><i class="glyphicon glyphicon-check readed" title="{{ _('Mark this article as read') }}"></i></a>
                                    {% if filter_ == 'all' %}</b>{% endif %}
                                {% endif %}
                            </td>
                            <td><a class="open-article" href="/article/redirect/{{ article.id}}" target="_blank">{{ article.source.title|safe }}</a></td>
                            <td {%if filter_ == 'all' and article.readed == False %}style='font-weight:bold'{% endif %}>
                                <a href="/article/{{ article.id }}">{{ article.title|safe }}</a>
                            </td>
                            <td class="date">{{ article.date|datetime }}</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
    </div><!-- /.container -->
{% endif %}
{% endblock %}